Document: acpi-call
Title: Debian acpi-call Manual
Author: <insert document author here>
Abstract: This manual describes what acpi-call is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acpi-call/acpi-call.sgml.gz

Format: postscript
Files: /usr/share/doc/acpi-call/acpi-call.ps.gz

Format: text
Files: /usr/share/doc/acpi-call/acpi-call.text.gz

Format: HTML
Index: /usr/share/doc/acpi-call/html/index.html
Files: /usr/share/doc/acpi-call/html/*.html
